### ISSUE TITLE
How to specify language during build

### ISSUE THREAD

**Issue by levino** [ObserverOfTime/jsonresume-theme-relaxed#2]
Hi there, I am interested in the i18n part: How does one specify the language during build time?

**Comment by ObserverOfTime** [comment]
You have to set the `meta["x-lang"]` property in `resume.json` to one of the supported languages.
To change it during build time you'd have to provide a different file (or modify it beforehand).

**Comment by levino** [comment]
I found it
https://github.com/ObserverOfTime/jsonresume-theme-relaxed/blob/ae176bcb5f9de0d97a7d2ded3be089eb0a20d7b4/src/resume.htmls#L37
So my `resume.json` has to look like:
```json
{
  "meta": {
    "x-lang": "de"
  }
}
```
That is not part of the official [`json-resume`-schema](https://jsonresume.org/schema/), is it?

**Comment by ObserverOfTime** [comment]
No, I've mentioned that in the readme (and hence the `x-` prefix).

**Comment by levino** [comment]
Kinda hidden at the end of the default-collapsed "Details" dropdown table :) Now I see it. Thanks for the pointer. Maybe we should have a discussion about i18n in the jsonresume.org repo since I think it is a very useful feature.
